### ISSUE TITLE
SHA256 sums in the Release file err as mismatches in Sileo.

### ISSUE THREAD

**Issue by cbyrne** [Shugabuga/Silica#21] opened 2020-04-14 18:47 UTC
When adding a repository to Sileo, it alerts that the Packages.xz hash is invalid.

Raw error message:
```
Error: Hash for Packages.xz from https://beta.renaitare.dev is invalid!
```

**Comment by Shugabuga** [comment] 2020-04-14 20:04
I can reproduce this in Sileo too. It's definitely a bug; I just observed this today on another Silica repo.

**Comment by cbyrne** [comment] 2020-04-14 20:07
Yeah. I commented out the xz stuff on my side for now. I’ll take a look at it properly in a few minutes and if I find anything I’ll make a PR

**Comment by Shugabuga** [comment] 2020-04-14 20:23
Okay, thank you for reporting this, too!

I just verified the hashes by hand. `cat Packages.xz | sha256sum` yields the response that Silica generates. Similarly, `ls -la | grep Packages.xz` does yield the same size that Silica appends, too.

This is a strange bug, but Silica is most likely involved because *this only happens to Silica repos*.

`https://patrik-svovodik.github.io/repo` also has this bug, despite [not having updated Silica in a year](https://patrik-svobodik.github.io/repo/api/about.json). However, previous versions of Sileo, which I tested Silica on, didn't err like this. Nor did Sileo do so yesterday.

`https://repo.shuga.co` also has this bug as of now. I don't recall this happening on older versions of Sileo; what does Silica do that these newer builds seem to dislike?

Zebra, Cydia (Diatrus fork) are unaffected.

**Comment by cbyrne** [comment] 2020-04-14 20:24
I’m not sure. 

I am part of the Sileo team and this appears to be something in Sileo acting up. In the morning I’ll do some debugging and test this and come back to you with more information.

**Comment by Shugabuga** [comment] 2020-04-14 20:31
Yeah, I'm thinking there's something Sileo doesn't like how the repo is formatted. Is it because Silica puts a space before the hash? Or maybe because Silica opts to put the hash in the first place (not many repos opt to put the hash in the `Release` file nowadays?

However, [Chariz, one of the few repos that both puts the hash and a leading space before the hash](https://repo.chariz.com/Release), seems to be working fine..?

I'd compare between the builds from Chimera (which worked fine) to the recent checkra1n builds.

**Comment by cbyrne** [comment] 2020-04-14 20:33
Yeah, it’s confusing. I’ll check tomorrow and if there’s a fix on Sileo’s side I’ll implement it and notify you when it’s done. If not I’ll make a PR to Silica

**Comment by Shugabuga** [comment] 2020-04-14 20:35
Alright, sounds good. 👍

Also: please let me know what the issue itself is, as I do know Silica can tend to be buggy/finicky with inputs.

**Comment by cbyrne** [comment] 2020-04-14 20:36
I will

**Comment by Patrik-svobodik** [comment] 2020-04-14 20:43
@Shugabuga just a reminder you misspelled that repo, it’s in fact patrik-svobodik, but that doesn’t matter, just so you can check it.

**Comment by coolstar** [comment] 2020-04-14 20:45
I think this is the issue: https://github.com/coolstar/SileoApp/commit/f14ae81f17274143e2e0ae1e78c0440c4adb767c (only Sileo team members can see it)

The fix has been committed to git 19 days ago, but is pending release

The issue is with too many spaces between hash components

**Comment by cbyrne** [comment] 2020-04-14 20:47
@coolstar Was just going to comment that after you told me haha, I’ll check tomorrow if that fixed the issue and if it does then this issue is no longer required

**Comment by Shugabuga** [comment] 2020-04-14 21:44
Hmm, too many spaces? In this sample from Renai's repo, there are three spaces (lead and padding the bytes used. Could it also be due to a lack of a newline (an issue I literally just noticed, d'oh!)?

```deb
 2bc2cace4b9b99760c63d10497942f1185bb08bd30ce0721d83a6b127f2ebc8b 476 Packages.bz2
```

**Comment by Shugabuga** [comment] 2020-04-14 21:55
I pushed a fix to what I think is the root of the problem. Let me know how it goes.

**Closed** 2020-04-14 21:54 UTC
Labels: bug, severe
