### ISSUE TITLE
Error by running index.py

### ISSUE THREAD

**Issue by neumaif02** [Shugabuga/Silica#16] opened 2019-10-01 15:10 UTC
`Silica Compiler 1.1.0
Traceback (most recent call last):
  File "index.py", line 226, in <module>
    main()
  File "index.py", line 53, in main
    tweak_release = PackageLister.GetTweakRelease()
  File "/home/nepeta/Downloads/Silica-master/util/PackageLister.py", line 55, in GetTweakRelease
    with open(self.root + "Packages/" + tweakEntry + "/silica_data/index.json", "r") as content_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nepeta/Downloads/Silica-master/util/../Packages/Test/silica_data/index.json'
`

**Comment by Shugabuga** [comment] 2019-10-01 23:07
Duplicate of #15.

**Closed by Shugabuga** 2019-10-01 23:07 UTC

**Comment by neumaif02** [comment] 2019-10-02 17:31
It's different, compare the errors.

**Comment by Shugabuga** [comment] 2019-10-04 15:49
I did. They're both errors caused by a missing or mal-formatted index.json file for the package. Python just complains slightly differently.

**Comment by neumaif02** [comment] 2019-10-04 15:56
How do I create a index.json file, I don’t have one created automattically.

Shuga <notifications@github.com> schrieb am Fr. 4. Okt. 2019 um 17:49:

**Comment by Shugabuga** [comment] 2019-10-04 16:06
Look at the README for an example of an index.json file. It'll go in the package's `silica_data` file.
